### ISSUE TITLE
is it possible to use this model on general sentences?

### ISSUE THREAD

**Issue by kasra-pak** [Sanqiang/text_simplification#10]
i'm trying to pass some sentences as input to the model and paraphrase them some how, do you think that this model works for me? also i really appreciate any hints or scripts for doing the above work

**Comment by Crista23** [comment]
Hi @kasra-pak , I am interested in doing the same. Did you receive an answer to your question?

**Comment by kasra-pak** [comment]
Hi @Crista23 , i think using translators would be an efficient approach (i.e. translating sentences to a second language and then translate them back to the main language) this may cause some change is words used in the language meanwhile keep the definition. also this can be a multilingual approach. by the way i didn't go further in that project and this was my last status. i hope that would help.

**Comment by Sanqiang** [comment]
It should be. For simple sentence input, it will just repeat input.
