### ISSUE TITLE
download links are invalid

### ISSUE THREAD

**Issue by junxu-ai** [Sanqiang/text_simplification#14]
Hi, 

It seems that the links are invalid now. https://drive.google.com/open?id=16gO8cLXttGR64_xvLHgMwgJeB1DzT93N
anyone can share a new link? 

Thanks,
Jun

**Comment by monkdou0** [comment]
Same question

**Comment by vladcioaba** [comment]
Same question

**Comment by Sanqiang** [comment]
Oh my Google drive has some issues, but another authors have a copy:
https://github.com/XingxingZhang/dress (check WikiLarge section)
