### ISSUE TITLE
Model output

### ISSUE THREAD

**Issue by Jmallins** [Sanqiang/text_simplification#2]
Hi would it be possible for you to share your model output on newsela + turk dataset.

Thank you!

**Comment by Jmallins** [comment]
Also, you mentioned in your paper that you would release your models, but I can't seem to find them. Could you point me to their location.

Thank you :)

**Comment by Sanqiang** [comment]
Just update the readme. You can download from Requirement: https://drive.google.com/file/d/1WzqE1ISbUQDuSnHwpevY7gsLEVp0zQzG/view?usp=sharing 
Will update the instruction recently.

**Comment by Sanqiang** [comment]
If you have further questions, please email me (I doesn't check Github Issues daily :))

**Comment by Sanqiang** [comment]
added.
