### ISSUE TITLE
Where is L_critic implemented?

### ISSUE THREAD

**Issue by mcs0042** [Sanqiang/text_simplification#6]
The file loss.py seems to contain a function for sequence loss, but not critic loss. In fact, after searching the repo for "critic_loss", "critic", "crit", and similar terms, I haven't been able to find the function anywhere. Do you mind referring me to the place in the code where L_critic is implemented?

Thanks for your time!

**Comment by chensongcan** [comment]
could you provide the dataset？

**Comment by Sanqiang** [comment]
It is here: https://github.com/Sanqiang/text_simplification/blob/c76a522827a90114e196b2e6ff7c2014ce48deff/model/graph.py#L531
see the variable decode_word_weight
