### ISSUE TITLE
Vocab Rules file missing 

### ISSUE THREAD

**Issue by DhairyaPatel7** [Sanqiang/text_simplification#9]
@Sanqiang Can you please provide the file for vocab rules `/zfs1/hdaqing/saz31/dataset/tmp_trans/ner/rule_vocab2`

**Comment by chensongcan** [comment]
@Sanqiang Could you please provide the file for dataset？
/zfs1/hdaqing/saz31/dataset/

**Comment by chensongcan** [comment]
@DhairyaPatel7  have your  solved your problem？

**Comment by Sanqiang** [comment]
Hmmm, actually the file is in my Google Drive, but my Google drive not work recently.
But that rule vocab file is simply a list of rules in Simple PPDB, you can download them here: http://www.seas.upenn.edu/˜nlp/
resources/simple-ppdb.tgz
in paper https://aclanthology.org/P16-2024.pdf
